# Generated by Django 4.2.7 on 2024-01-19 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_userreport'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userreport',
            old_name='register_date',
            new_name='created',
        ),
    ]
